name: TestPlugin2
version: 1.0
main: gg.stephen.test.TestPlugin2
api-version: 1.20
description: Super cool test plugin!
author: Stephen
contributors: [Brandon, Josh]
website: https://mcworkshop.org
depend: [TestPlugin]